version: '3.3'
services:

  # php:
  #   image: php:8-apache
  #   ports:
  #     - 95:80
  #   volumes:
  #     - ./www:/www
  ton_web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: ton_web
    volumes:
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./www:/www
    env_file: .env
    #ports:
    #  - 95:80
    depends_on:
      - ton_mysql
    networks:
      - ton-network

  ton_nginx:
    image: nginx:latest
    container_name: ton_nginx
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - ./www:/www
    env_file: .env
    ports:
      - 87:80
    links:
      - ton_web
    networks:
      - ton-network

  ton_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ton_pma
    environment:
      PMA_HOST: ton_mysql
    depends_on:
      - ton_mysql
    ports:
        - 84:80
    networks:
      - ton-network

  # ton_adminer:
  #   image: adminer
  #   container_name: spa_adminer
  #   ports:
  #     - 8080:8080
  #   links:
  #    - db 

  ton_mysql:
    #image: mariadb
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: ton_mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      #MYSQL_ROOT_HOST: '%' #For external access. Uncommet, if you need
    restart: always
    ports:
      - '3307:3306'
    networks:
      - ton-network

volumes:
  ton_mysql:
  ton_web:
  ton_nginx:
    driver: local

networks:
  ton-network:
    driver: bridge